name: Develop Build Task

on:
  # push:
  #   branches:
  #     - develop
  pull_request:
    branches:
      - test-ci

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[skip ci]') == false"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '18.18.0'

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git fetch --all
        git checkout ${{ github.event.pull_request.head.ref }}

    # - name: Authenticate with npm
    #   run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

    # - name: Install dependencies
    #   run: yarn install

    # - name: Build
    #   run: yarn build

    - name: test git push
      run: echo 'skip ci' > skip.ci.text

    # - name: release
    #   run: npm run release
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    #     PAT: ${{ secrets.PAT_TOKEN }}

    - name: Commit and push changes
      run: |
        echo "https://x-access-token:${ACTIONS_DEPLOY_KEY}@github.com/${{ github.repository }}.git"
        git remote -v
        git add .
        git commit -m "[skip ci] skip ci Apply CI changes"
        git remote set-url origin https://x-access-token:${ACTIONS_DEPLOY_KEY}@github.com/${{ github.repository }}.git
        git push origin ${{ github.head_ref }}
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}

    
    

