name: Develop Build Task

on:
  # push:
  #   branches:
  #     - develop
  pull_request:
    branches:
      - test-ci

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[skip ci]') == false"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git fetch --all
        git checkout ${{ github.event.pull_request.head.ref }}

    - name: Commit and push changes
      run: |
        echo "https://qlover:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git"
        echo 'skip ci' > skip.ci.text
        git add .
        git commit -m "[skip ci] skip ci Apply CI changes"
        git remote set-url origin https://qlover:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
        git remote -v
        git push origin ${{ github.head_ref }}
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}


    
    

